[package]
name = "rust-synth-gui"
version = "0.1.0"
authors = ["Victor Basso <vitobasso@gmail.com>"]
edition = "2018"

[dependencies]
rust-synth = { git = "https://github.com/vitobasso/rust-synth.git" }
piston_window = "0.87.0"